// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buildingSiteMonitoring.proto

package ds.buildingSiteMonitoring;

public interface AreaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:buildingSiteMonitoring.AreaResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 materialUsage = 1;</code>
   */
  int getMaterialUsage();

  /**
   * <code>string issues = 2;</code>
   */
  java.lang.String getIssues();
  /**
   * <code>string issues = 2;</code>
   */
  com.google.protobuf.ByteString
      getIssuesBytes();
}
