// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buildingSiteMonitoring.proto

package ds.buildingSiteMonitoring;

/**
 * Protobuf type {@code buildingSiteMonitoring.AreaResponse}
 */
public  final class AreaResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:buildingSiteMonitoring.AreaResponse)
    AreaResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AreaResponse.newBuilder() to construct.
  private AreaResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AreaResponse() {
    materialUsage_ = 0;
    issues_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AreaResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            materialUsage_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            issues_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.buildingSiteMonitoring.BuildingSiteMonitoringImpl.internal_static_buildingSiteMonitoring_AreaResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.buildingSiteMonitoring.BuildingSiteMonitoringImpl.internal_static_buildingSiteMonitoring_AreaResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.buildingSiteMonitoring.AreaResponse.class, ds.buildingSiteMonitoring.AreaResponse.Builder.class);
  }

  public static final int MATERIALUSAGE_FIELD_NUMBER = 1;
  private int materialUsage_;
  /**
   * <code>int32 materialUsage = 1;</code>
   */
  public int getMaterialUsage() {
    return materialUsage_;
  }

  public static final int ISSUES_FIELD_NUMBER = 2;
  private volatile java.lang.Object issues_;
  /**
   * <code>string issues = 2;</code>
   */
  public java.lang.String getIssues() {
    java.lang.Object ref = issues_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      issues_ = s;
      return s;
    }
  }
  /**
   * <code>string issues = 2;</code>
   */
  public com.google.protobuf.ByteString
      getIssuesBytes() {
    java.lang.Object ref = issues_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      issues_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (materialUsage_ != 0) {
      output.writeInt32(1, materialUsage_);
    }
    if (!getIssuesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, issues_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (materialUsage_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, materialUsage_);
    }
    if (!getIssuesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, issues_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.buildingSiteMonitoring.AreaResponse)) {
      return super.equals(obj);
    }
    ds.buildingSiteMonitoring.AreaResponse other = (ds.buildingSiteMonitoring.AreaResponse) obj;

    boolean result = true;
    result = result && (getMaterialUsage()
        == other.getMaterialUsage());
    result = result && getIssues()
        .equals(other.getIssues());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MATERIALUSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMaterialUsage();
    hash = (37 * hash) + ISSUES_FIELD_NUMBER;
    hash = (53 * hash) + getIssues().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.buildingSiteMonitoring.AreaResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.buildingSiteMonitoring.AreaResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.buildingSiteMonitoring.AreaResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.buildingSiteMonitoring.AreaResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.buildingSiteMonitoring.AreaResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.buildingSiteMonitoring.AreaResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.buildingSiteMonitoring.AreaResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.buildingSiteMonitoring.AreaResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.buildingSiteMonitoring.AreaResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.buildingSiteMonitoring.AreaResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.buildingSiteMonitoring.AreaResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.buildingSiteMonitoring.AreaResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.buildingSiteMonitoring.AreaResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code buildingSiteMonitoring.AreaResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:buildingSiteMonitoring.AreaResponse)
      ds.buildingSiteMonitoring.AreaResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.buildingSiteMonitoring.BuildingSiteMonitoringImpl.internal_static_buildingSiteMonitoring_AreaResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.buildingSiteMonitoring.BuildingSiteMonitoringImpl.internal_static_buildingSiteMonitoring_AreaResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.buildingSiteMonitoring.AreaResponse.class, ds.buildingSiteMonitoring.AreaResponse.Builder.class);
    }

    // Construct using ds.buildingSiteMonitoring.AreaResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      materialUsage_ = 0;

      issues_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.buildingSiteMonitoring.BuildingSiteMonitoringImpl.internal_static_buildingSiteMonitoring_AreaResponse_descriptor;
    }

    @java.lang.Override
    public ds.buildingSiteMonitoring.AreaResponse getDefaultInstanceForType() {
      return ds.buildingSiteMonitoring.AreaResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.buildingSiteMonitoring.AreaResponse build() {
      ds.buildingSiteMonitoring.AreaResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.buildingSiteMonitoring.AreaResponse buildPartial() {
      ds.buildingSiteMonitoring.AreaResponse result = new ds.buildingSiteMonitoring.AreaResponse(this);
      result.materialUsage_ = materialUsage_;
      result.issues_ = issues_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.buildingSiteMonitoring.AreaResponse) {
        return mergeFrom((ds.buildingSiteMonitoring.AreaResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.buildingSiteMonitoring.AreaResponse other) {
      if (other == ds.buildingSiteMonitoring.AreaResponse.getDefaultInstance()) return this;
      if (other.getMaterialUsage() != 0) {
        setMaterialUsage(other.getMaterialUsage());
      }
      if (!other.getIssues().isEmpty()) {
        issues_ = other.issues_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.buildingSiteMonitoring.AreaResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.buildingSiteMonitoring.AreaResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int materialUsage_ ;
    /**
     * <code>int32 materialUsage = 1;</code>
     */
    public int getMaterialUsage() {
      return materialUsage_;
    }
    /**
     * <code>int32 materialUsage = 1;</code>
     */
    public Builder setMaterialUsage(int value) {
      
      materialUsage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 materialUsage = 1;</code>
     */
    public Builder clearMaterialUsage() {
      
      materialUsage_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object issues_ = "";
    /**
     * <code>string issues = 2;</code>
     */
    public java.lang.String getIssues() {
      java.lang.Object ref = issues_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        issues_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string issues = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIssuesBytes() {
      java.lang.Object ref = issues_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        issues_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string issues = 2;</code>
     */
    public Builder setIssues(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      issues_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string issues = 2;</code>
     */
    public Builder clearIssues() {
      
      issues_ = getDefaultInstance().getIssues();
      onChanged();
      return this;
    }
    /**
     * <code>string issues = 2;</code>
     */
    public Builder setIssuesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      issues_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:buildingSiteMonitoring.AreaResponse)
  }

  // @@protoc_insertion_point(class_scope:buildingSiteMonitoring.AreaResponse)
  private static final ds.buildingSiteMonitoring.AreaResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.buildingSiteMonitoring.AreaResponse();
  }

  public static ds.buildingSiteMonitoring.AreaResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AreaResponse>
      PARSER = new com.google.protobuf.AbstractParser<AreaResponse>() {
    @java.lang.Override
    public AreaResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AreaResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AreaResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AreaResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.buildingSiteMonitoring.AreaResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

