// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buildingSiteMonitoring.proto

package ds.buildingSiteMonitoring;

public final class BuildingSiteMonitoringImpl {
  private BuildingSiteMonitoringImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buildingSiteMonitoring_AreaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buildingSiteMonitoring_AreaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buildingSiteMonitoring_AreaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buildingSiteMonitoring_AreaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buildingSiteMonitoring_SensorDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buildingSiteMonitoring_SensorDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buildingSiteMonitoring_SensorDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buildingSiteMonitoring_SensorDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034buildingSiteMonitoring.proto\022\026building" +
      "SiteMonitoring\"\037\n\013AreaRequest\022\020\n\010areaNam" +
      "e\030\001 \001(\t\"5\n\014AreaResponse\022\025\n\rmaterialUsage" +
      "\030\001 \001(\005\022\016\n\006issues\030\002 \001(\t\"R\n\021SensorDataRequ" +
      "est\022\020\n\010areaName\030\001 \001(\t\022\025\n\rmaterialUsage\030\002" +
      " \001(\005\022\024\n\014materialLeft\030\003 \001(\t\";\n\022SensorData" +
      "Response\022\r\n\005alert\030\001 \001(\t\022\026\n\016recommendatio" +
      "n\030\002 \001(\t2\350\001\n\031BuildingMonitoringService\022\\\n" +
      "\013MonitorArea\022#.buildingSiteMonitoring.Ar" +
      "eaRequest\032$.buildingSiteMonitoring.AreaR" +
      "esponse\"\0000\001\022m\n\016SendSensorData\022).building" +
      "SiteMonitoring.SensorDataRequest\032*.build" +
      "ingSiteMonitoring.SensorDataResponse\"\000(\001" +
      "0\001B9\n\031ds.buildingSiteMonitoringB\032Buildin" +
      "gSiteMonitoringImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_buildingSiteMonitoring_AreaRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_buildingSiteMonitoring_AreaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buildingSiteMonitoring_AreaRequest_descriptor,
        new java.lang.String[] { "AreaName", });
    internal_static_buildingSiteMonitoring_AreaResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_buildingSiteMonitoring_AreaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buildingSiteMonitoring_AreaResponse_descriptor,
        new java.lang.String[] { "MaterialUsage", "Issues", });
    internal_static_buildingSiteMonitoring_SensorDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_buildingSiteMonitoring_SensorDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buildingSiteMonitoring_SensorDataRequest_descriptor,
        new java.lang.String[] { "AreaName", "MaterialUsage", "MaterialLeft", });
    internal_static_buildingSiteMonitoring_SensorDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_buildingSiteMonitoring_SensorDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buildingSiteMonitoring_SensorDataResponse_descriptor,
        new java.lang.String[] { "Alert", "Recommendation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
