// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buildingSiteMonitoring.proto

package ds.buildingSiteMonitoring;

public interface SensorDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:buildingSiteMonitoring.SensorDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string alert = 1;</code>
   */
  java.lang.String getAlert();
  /**
   * <code>string alert = 1;</code>
   */
  com.google.protobuf.ByteString
      getAlertBytes();

  /**
   * <code>string recommendation = 2;</code>
   */
  java.lang.String getRecommendation();
  /**
   * <code>string recommendation = 2;</code>
   */
  com.google.protobuf.ByteString
      getRecommendationBytes();
}
