// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buildingSiteMonitoring.proto

package ds.buildingSiteMonitoring;

/**
 * Protobuf type {@code buildingSiteMonitoring.SensorDataRequest}
 */
public  final class SensorDataRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:buildingSiteMonitoring.SensorDataRequest)
    SensorDataRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SensorDataRequest.newBuilder() to construct.
  private SensorDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SensorDataRequest() {
    areaName_ = "";
    materialUsage_ = 0;
    materialLeft_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SensorDataRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            areaName_ = s;
            break;
          }
          case 16: {

            materialUsage_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            materialLeft_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.buildingSiteMonitoring.BuildingSiteMonitoringImpl.internal_static_buildingSiteMonitoring_SensorDataRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.buildingSiteMonitoring.BuildingSiteMonitoringImpl.internal_static_buildingSiteMonitoring_SensorDataRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.buildingSiteMonitoring.SensorDataRequest.class, ds.buildingSiteMonitoring.SensorDataRequest.Builder.class);
  }

  public static final int AREANAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object areaName_;
  /**
   * <code>string areaName = 1;</code>
   */
  public java.lang.String getAreaName() {
    java.lang.Object ref = areaName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      areaName_ = s;
      return s;
    }
  }
  /**
   * <code>string areaName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAreaNameBytes() {
    java.lang.Object ref = areaName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      areaName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MATERIALUSAGE_FIELD_NUMBER = 2;
  private int materialUsage_;
  /**
   * <code>int32 materialUsage = 2;</code>
   */
  public int getMaterialUsage() {
    return materialUsage_;
  }

  public static final int MATERIALLEFT_FIELD_NUMBER = 3;
  private volatile java.lang.Object materialLeft_;
  /**
   * <code>string materialLeft = 3;</code>
   */
  public java.lang.String getMaterialLeft() {
    java.lang.Object ref = materialLeft_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      materialLeft_ = s;
      return s;
    }
  }
  /**
   * <code>string materialLeft = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMaterialLeftBytes() {
    java.lang.Object ref = materialLeft_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      materialLeft_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAreaNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, areaName_);
    }
    if (materialUsage_ != 0) {
      output.writeInt32(2, materialUsage_);
    }
    if (!getMaterialLeftBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, materialLeft_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAreaNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, areaName_);
    }
    if (materialUsage_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, materialUsage_);
    }
    if (!getMaterialLeftBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, materialLeft_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.buildingSiteMonitoring.SensorDataRequest)) {
      return super.equals(obj);
    }
    ds.buildingSiteMonitoring.SensorDataRequest other = (ds.buildingSiteMonitoring.SensorDataRequest) obj;

    boolean result = true;
    result = result && getAreaName()
        .equals(other.getAreaName());
    result = result && (getMaterialUsage()
        == other.getMaterialUsage());
    result = result && getMaterialLeft()
        .equals(other.getMaterialLeft());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AREANAME_FIELD_NUMBER;
    hash = (53 * hash) + getAreaName().hashCode();
    hash = (37 * hash) + MATERIALUSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMaterialUsage();
    hash = (37 * hash) + MATERIALLEFT_FIELD_NUMBER;
    hash = (53 * hash) + getMaterialLeft().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.buildingSiteMonitoring.SensorDataRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.buildingSiteMonitoring.SensorDataRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.buildingSiteMonitoring.SensorDataRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.buildingSiteMonitoring.SensorDataRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.buildingSiteMonitoring.SensorDataRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.buildingSiteMonitoring.SensorDataRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.buildingSiteMonitoring.SensorDataRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.buildingSiteMonitoring.SensorDataRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.buildingSiteMonitoring.SensorDataRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.buildingSiteMonitoring.SensorDataRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.buildingSiteMonitoring.SensorDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.buildingSiteMonitoring.SensorDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.buildingSiteMonitoring.SensorDataRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code buildingSiteMonitoring.SensorDataRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:buildingSiteMonitoring.SensorDataRequest)
      ds.buildingSiteMonitoring.SensorDataRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.buildingSiteMonitoring.BuildingSiteMonitoringImpl.internal_static_buildingSiteMonitoring_SensorDataRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.buildingSiteMonitoring.BuildingSiteMonitoringImpl.internal_static_buildingSiteMonitoring_SensorDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.buildingSiteMonitoring.SensorDataRequest.class, ds.buildingSiteMonitoring.SensorDataRequest.Builder.class);
    }

    // Construct using ds.buildingSiteMonitoring.SensorDataRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      areaName_ = "";

      materialUsage_ = 0;

      materialLeft_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.buildingSiteMonitoring.BuildingSiteMonitoringImpl.internal_static_buildingSiteMonitoring_SensorDataRequest_descriptor;
    }

    @java.lang.Override
    public ds.buildingSiteMonitoring.SensorDataRequest getDefaultInstanceForType() {
      return ds.buildingSiteMonitoring.SensorDataRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ds.buildingSiteMonitoring.SensorDataRequest build() {
      ds.buildingSiteMonitoring.SensorDataRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.buildingSiteMonitoring.SensorDataRequest buildPartial() {
      ds.buildingSiteMonitoring.SensorDataRequest result = new ds.buildingSiteMonitoring.SensorDataRequest(this);
      result.areaName_ = areaName_;
      result.materialUsage_ = materialUsage_;
      result.materialLeft_ = materialLeft_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.buildingSiteMonitoring.SensorDataRequest) {
        return mergeFrom((ds.buildingSiteMonitoring.SensorDataRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.buildingSiteMonitoring.SensorDataRequest other) {
      if (other == ds.buildingSiteMonitoring.SensorDataRequest.getDefaultInstance()) return this;
      if (!other.getAreaName().isEmpty()) {
        areaName_ = other.areaName_;
        onChanged();
      }
      if (other.getMaterialUsage() != 0) {
        setMaterialUsage(other.getMaterialUsage());
      }
      if (!other.getMaterialLeft().isEmpty()) {
        materialLeft_ = other.materialLeft_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.buildingSiteMonitoring.SensorDataRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.buildingSiteMonitoring.SensorDataRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object areaName_ = "";
    /**
     * <code>string areaName = 1;</code>
     */
    public java.lang.String getAreaName() {
      java.lang.Object ref = areaName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        areaName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string areaName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAreaNameBytes() {
      java.lang.Object ref = areaName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        areaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string areaName = 1;</code>
     */
    public Builder setAreaName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      areaName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string areaName = 1;</code>
     */
    public Builder clearAreaName() {
      
      areaName_ = getDefaultInstance().getAreaName();
      onChanged();
      return this;
    }
    /**
     * <code>string areaName = 1;</code>
     */
    public Builder setAreaNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      areaName_ = value;
      onChanged();
      return this;
    }

    private int materialUsage_ ;
    /**
     * <code>int32 materialUsage = 2;</code>
     */
    public int getMaterialUsage() {
      return materialUsage_;
    }
    /**
     * <code>int32 materialUsage = 2;</code>
     */
    public Builder setMaterialUsage(int value) {
      
      materialUsage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 materialUsage = 2;</code>
     */
    public Builder clearMaterialUsage() {
      
      materialUsage_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object materialLeft_ = "";
    /**
     * <code>string materialLeft = 3;</code>
     */
    public java.lang.String getMaterialLeft() {
      java.lang.Object ref = materialLeft_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        materialLeft_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string materialLeft = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMaterialLeftBytes() {
      java.lang.Object ref = materialLeft_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        materialLeft_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string materialLeft = 3;</code>
     */
    public Builder setMaterialLeft(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      materialLeft_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string materialLeft = 3;</code>
     */
    public Builder clearMaterialLeft() {
      
      materialLeft_ = getDefaultInstance().getMaterialLeft();
      onChanged();
      return this;
    }
    /**
     * <code>string materialLeft = 3;</code>
     */
    public Builder setMaterialLeftBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      materialLeft_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:buildingSiteMonitoring.SensorDataRequest)
  }

  // @@protoc_insertion_point(class_scope:buildingSiteMonitoring.SensorDataRequest)
  private static final ds.buildingSiteMonitoring.SensorDataRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.buildingSiteMonitoring.SensorDataRequest();
  }

  public static ds.buildingSiteMonitoring.SensorDataRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SensorDataRequest>
      PARSER = new com.google.protobuf.AbstractParser<SensorDataRequest>() {
    @java.lang.Override
    public SensorDataRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SensorDataRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SensorDataRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SensorDataRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.buildingSiteMonitoring.SensorDataRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

