// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buildingSiteMonitoring.proto

package ds.buildingSiteMonitoring;

public interface SensorDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:buildingSiteMonitoring.SensorDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string areaName = 1;</code>
   */
  java.lang.String getAreaName();
  /**
   * <code>string areaName = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaNameBytes();

  /**
   * <code>int32 materialUsage = 2;</code>
   */
  int getMaterialUsage();

  /**
   * <code>string materialLeft = 3;</code>
   */
  java.lang.String getMaterialLeft();
  /**
   * <code>string materialLeft = 3;</code>
   */
  com.google.protobuf.ByteString
      getMaterialLeftBytes();
}
