// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: propertyMarket.proto

package ds.propertyMarket;

public interface desiredPropertyAvailableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:propertyMarket.desiredPropertyAvailable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 desiredAvailable = 1;</code>
   */
  int getDesiredAvailable();
}
