// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: propertyMarket.proto

package ds.propertyMarket;

/**
 * Protobuf type {@code propertyMarket.PropertyAvailableConfirm}
 */
public  final class PropertyAvailableConfirm extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:propertyMarket.PropertyAvailableConfirm)
    PropertyAvailableConfirmOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PropertyAvailableConfirm.newBuilder() to construct.
  private PropertyAvailableConfirm(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PropertyAvailableConfirm() {
    currentPropertyAvailable_ = 0;
    confirmation_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PropertyAvailableConfirm(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            currentPropertyAvailable_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            confirmation_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.propertyMarket.propertyMarketImpl.internal_static_propertyMarket_PropertyAvailableConfirm_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.propertyMarket.propertyMarketImpl.internal_static_propertyMarket_PropertyAvailableConfirm_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.propertyMarket.PropertyAvailableConfirm.class, ds.propertyMarket.PropertyAvailableConfirm.Builder.class);
  }

  public static final int CURRENTPROPERTYAVAILABLE_FIELD_NUMBER = 1;
  private int currentPropertyAvailable_;
  /**
   * <code>int32 currentPropertyAvailable = 1;</code>
   */
  public int getCurrentPropertyAvailable() {
    return currentPropertyAvailable_;
  }

  public static final int CONFIRMATION_FIELD_NUMBER = 2;
  private volatile java.lang.Object confirmation_;
  /**
   * <code>string confirmation = 2;</code>
   */
  public java.lang.String getConfirmation() {
    java.lang.Object ref = confirmation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      confirmation_ = s;
      return s;
    }
  }
  /**
   * <code>string confirmation = 2;</code>
   */
  public com.google.protobuf.ByteString
      getConfirmationBytes() {
    java.lang.Object ref = confirmation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      confirmation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (currentPropertyAvailable_ != 0) {
      output.writeInt32(1, currentPropertyAvailable_);
    }
    if (!getConfirmationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, confirmation_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (currentPropertyAvailable_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, currentPropertyAvailable_);
    }
    if (!getConfirmationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, confirmation_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.propertyMarket.PropertyAvailableConfirm)) {
      return super.equals(obj);
    }
    ds.propertyMarket.PropertyAvailableConfirm other = (ds.propertyMarket.PropertyAvailableConfirm) obj;

    boolean result = true;
    result = result && (getCurrentPropertyAvailable()
        == other.getCurrentPropertyAvailable());
    result = result && getConfirmation()
        .equals(other.getConfirmation());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENTPROPERTYAVAILABLE_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentPropertyAvailable();
    hash = (37 * hash) + CONFIRMATION_FIELD_NUMBER;
    hash = (53 * hash) + getConfirmation().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.propertyMarket.PropertyAvailableConfirm parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.propertyMarket.PropertyAvailableConfirm parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.propertyMarket.PropertyAvailableConfirm parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.propertyMarket.PropertyAvailableConfirm parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.propertyMarket.PropertyAvailableConfirm parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.propertyMarket.PropertyAvailableConfirm parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.propertyMarket.PropertyAvailableConfirm parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.propertyMarket.PropertyAvailableConfirm parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.propertyMarket.PropertyAvailableConfirm parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.propertyMarket.PropertyAvailableConfirm parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.propertyMarket.PropertyAvailableConfirm parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.propertyMarket.PropertyAvailableConfirm parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.propertyMarket.PropertyAvailableConfirm prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code propertyMarket.PropertyAvailableConfirm}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:propertyMarket.PropertyAvailableConfirm)
      ds.propertyMarket.PropertyAvailableConfirmOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.propertyMarket.propertyMarketImpl.internal_static_propertyMarket_PropertyAvailableConfirm_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.propertyMarket.propertyMarketImpl.internal_static_propertyMarket_PropertyAvailableConfirm_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.propertyMarket.PropertyAvailableConfirm.class, ds.propertyMarket.PropertyAvailableConfirm.Builder.class);
    }

    // Construct using ds.propertyMarket.PropertyAvailableConfirm.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      currentPropertyAvailable_ = 0;

      confirmation_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.propertyMarket.propertyMarketImpl.internal_static_propertyMarket_PropertyAvailableConfirm_descriptor;
    }

    @java.lang.Override
    public ds.propertyMarket.PropertyAvailableConfirm getDefaultInstanceForType() {
      return ds.propertyMarket.PropertyAvailableConfirm.getDefaultInstance();
    }

    @java.lang.Override
    public ds.propertyMarket.PropertyAvailableConfirm build() {
      ds.propertyMarket.PropertyAvailableConfirm result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.propertyMarket.PropertyAvailableConfirm buildPartial() {
      ds.propertyMarket.PropertyAvailableConfirm result = new ds.propertyMarket.PropertyAvailableConfirm(this);
      result.currentPropertyAvailable_ = currentPropertyAvailable_;
      result.confirmation_ = confirmation_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.propertyMarket.PropertyAvailableConfirm) {
        return mergeFrom((ds.propertyMarket.PropertyAvailableConfirm)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.propertyMarket.PropertyAvailableConfirm other) {
      if (other == ds.propertyMarket.PropertyAvailableConfirm.getDefaultInstance()) return this;
      if (other.getCurrentPropertyAvailable() != 0) {
        setCurrentPropertyAvailable(other.getCurrentPropertyAvailable());
      }
      if (!other.getConfirmation().isEmpty()) {
        confirmation_ = other.confirmation_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.propertyMarket.PropertyAvailableConfirm parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.propertyMarket.PropertyAvailableConfirm) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int currentPropertyAvailable_ ;
    /**
     * <code>int32 currentPropertyAvailable = 1;</code>
     */
    public int getCurrentPropertyAvailable() {
      return currentPropertyAvailable_;
    }
    /**
     * <code>int32 currentPropertyAvailable = 1;</code>
     */
    public Builder setCurrentPropertyAvailable(int value) {
      
      currentPropertyAvailable_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 currentPropertyAvailable = 1;</code>
     */
    public Builder clearCurrentPropertyAvailable() {
      
      currentPropertyAvailable_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object confirmation_ = "";
    /**
     * <code>string confirmation = 2;</code>
     */
    public java.lang.String getConfirmation() {
      java.lang.Object ref = confirmation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        confirmation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string confirmation = 2;</code>
     */
    public com.google.protobuf.ByteString
        getConfirmationBytes() {
      java.lang.Object ref = confirmation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        confirmation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string confirmation = 2;</code>
     */
    public Builder setConfirmation(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      confirmation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string confirmation = 2;</code>
     */
    public Builder clearConfirmation() {
      
      confirmation_ = getDefaultInstance().getConfirmation();
      onChanged();
      return this;
    }
    /**
     * <code>string confirmation = 2;</code>
     */
    public Builder setConfirmationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      confirmation_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:propertyMarket.PropertyAvailableConfirm)
  }

  // @@protoc_insertion_point(class_scope:propertyMarket.PropertyAvailableConfirm)
  private static final ds.propertyMarket.PropertyAvailableConfirm DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.propertyMarket.PropertyAvailableConfirm();
  }

  public static ds.propertyMarket.PropertyAvailableConfirm getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PropertyAvailableConfirm>
      PARSER = new com.google.protobuf.AbstractParser<PropertyAvailableConfirm>() {
    @java.lang.Override
    public PropertyAvailableConfirm parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PropertyAvailableConfirm(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PropertyAvailableConfirm> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PropertyAvailableConfirm> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.propertyMarket.PropertyAvailableConfirm getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

