// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: propertyMarket.proto

package ds.propertyMarket;

public interface PropertyAvailableConfirmOrBuilder extends
    // @@protoc_insertion_point(interface_extends:propertyMarket.PropertyAvailableConfirm)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 currentPropertyAvailable = 1;</code>
   */
  int getCurrentPropertyAvailable();

  /**
   * <code>string confirmation = 2;</code>
   */
  java.lang.String getConfirmation();
  /**
   * <code>string confirmation = 2;</code>
   */
  com.google.protobuf.ByteString
      getConfirmationBytes();
}
