// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: propertyMarket.proto

package ds.propertyMarket;

public final class propertyMarketImpl {
  private propertyMarketImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_propertyMarket_desiredPropertyAvailable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_propertyMarket_desiredPropertyAvailable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_propertyMarket_PropertyAvailableConfirm_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_propertyMarket_PropertyAvailableConfirm_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_propertyMarket_TenantsVolatilityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_propertyMarket_TenantsVolatilityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_propertyMarket_TenantsVolatilityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_propertyMarket_TenantsVolatilityResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024propertyMarket.proto\022\016propertyMarket\"4" +
      "\n\030desiredPropertyAvailable\022\030\n\020desiredAva" +
      "ilable\030\001 \001(\005\"R\n\030PropertyAvailableConfirm" +
      "\022 \n\030currentPropertyAvailable\030\001 \001(\005\022\024\n\014co" +
      "nfirmation\030\002 \001(\t\"\202\001\n\030TenantsVolatilityRe" +
      "quest\022\035\n\025freePropertyAvailable\030\001 \001(\005\022\025\n\r" +
      "tenantsNumber\030\002 \001(\005\022\032\n\022occupiedPropertie" +
      "s\030\003 \001(\005\022\024\n\014waitingQueue\030\004 \001(\005\"3\n\031Tenants" +
      "VolatilityResponse\022\026\n\016recommendation\030\001 \001" +
      "(\t2\372\001\n\025PropertyMarketService\022o\n\027SetPrope" +
      "rtyAvailability\022(.propertyMarket.desired" +
      "PropertyAvailable\032(.propertyMarket.Prope" +
      "rtyAvailableConfirm\"\000\022p\n\025SendTenantsVola" +
      "tility\022(.propertyMarket.TenantsVolatilit" +
      "yRequest\032).propertyMarket.TenantsVolatil" +
      "ityResponse\"\000(\001B)\n\021ds.propertyMarketB\022pr" +
      "opertyMarketImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_propertyMarket_desiredPropertyAvailable_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_propertyMarket_desiredPropertyAvailable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_propertyMarket_desiredPropertyAvailable_descriptor,
        new java.lang.String[] { "DesiredAvailable", });
    internal_static_propertyMarket_PropertyAvailableConfirm_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_propertyMarket_PropertyAvailableConfirm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_propertyMarket_PropertyAvailableConfirm_descriptor,
        new java.lang.String[] { "CurrentPropertyAvailable", "Confirmation", });
    internal_static_propertyMarket_TenantsVolatilityRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_propertyMarket_TenantsVolatilityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_propertyMarket_TenantsVolatilityRequest_descriptor,
        new java.lang.String[] { "FreePropertyAvailable", "TenantsNumber", "OccupiedProperties", "WaitingQueue", });
    internal_static_propertyMarket_TenantsVolatilityResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_propertyMarket_TenantsVolatilityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_propertyMarket_TenantsVolatilityResponse_descriptor,
        new java.lang.String[] { "Recommendation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
