// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: propertyMarket.proto

package ds.propertyMarket;

public interface TenantsVolatilityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:propertyMarket.TenantsVolatilityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 freePropertyAvailable = 1;</code>
   */
  int getFreePropertyAvailable();

  /**
   * <code>int32 tenantsNumber = 2;</code>
   */
  int getTenantsNumber();

  /**
   * <code>int32 occupiedProperties = 3;</code>
   */
  int getOccupiedProperties();

  /**
   * <code>int32 waitingQueue = 4;</code>
   */
  int getWaitingQueue();
}
