// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: propertyMarket.proto

package ds.propertyMarket;

/**
 * Protobuf type {@code propertyMarket.TenantsVolatilityRequest}
 */
public  final class TenantsVolatilityRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:propertyMarket.TenantsVolatilityRequest)
    TenantsVolatilityRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TenantsVolatilityRequest.newBuilder() to construct.
  private TenantsVolatilityRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TenantsVolatilityRequest() {
    freePropertyAvailable_ = 0;
    tenantsNumber_ = 0;
    occupiedProperties_ = 0;
    waitingQueue_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TenantsVolatilityRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            freePropertyAvailable_ = input.readInt32();
            break;
          }
          case 16: {

            tenantsNumber_ = input.readInt32();
            break;
          }
          case 24: {

            occupiedProperties_ = input.readInt32();
            break;
          }
          case 32: {

            waitingQueue_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.propertyMarket.propertyMarketImpl.internal_static_propertyMarket_TenantsVolatilityRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.propertyMarket.propertyMarketImpl.internal_static_propertyMarket_TenantsVolatilityRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.propertyMarket.TenantsVolatilityRequest.class, ds.propertyMarket.TenantsVolatilityRequest.Builder.class);
  }

  public static final int FREEPROPERTYAVAILABLE_FIELD_NUMBER = 1;
  private int freePropertyAvailable_;
  /**
   * <code>int32 freePropertyAvailable = 1;</code>
   */
  public int getFreePropertyAvailable() {
    return freePropertyAvailable_;
  }

  public static final int TENANTSNUMBER_FIELD_NUMBER = 2;
  private int tenantsNumber_;
  /**
   * <code>int32 tenantsNumber = 2;</code>
   */
  public int getTenantsNumber() {
    return tenantsNumber_;
  }

  public static final int OCCUPIEDPROPERTIES_FIELD_NUMBER = 3;
  private int occupiedProperties_;
  /**
   * <code>int32 occupiedProperties = 3;</code>
   */
  public int getOccupiedProperties() {
    return occupiedProperties_;
  }

  public static final int WAITINGQUEUE_FIELD_NUMBER = 4;
  private int waitingQueue_;
  /**
   * <code>int32 waitingQueue = 4;</code>
   */
  public int getWaitingQueue() {
    return waitingQueue_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (freePropertyAvailable_ != 0) {
      output.writeInt32(1, freePropertyAvailable_);
    }
    if (tenantsNumber_ != 0) {
      output.writeInt32(2, tenantsNumber_);
    }
    if (occupiedProperties_ != 0) {
      output.writeInt32(3, occupiedProperties_);
    }
    if (waitingQueue_ != 0) {
      output.writeInt32(4, waitingQueue_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (freePropertyAvailable_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, freePropertyAvailable_);
    }
    if (tenantsNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, tenantsNumber_);
    }
    if (occupiedProperties_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, occupiedProperties_);
    }
    if (waitingQueue_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, waitingQueue_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.propertyMarket.TenantsVolatilityRequest)) {
      return super.equals(obj);
    }
    ds.propertyMarket.TenantsVolatilityRequest other = (ds.propertyMarket.TenantsVolatilityRequest) obj;

    boolean result = true;
    result = result && (getFreePropertyAvailable()
        == other.getFreePropertyAvailable());
    result = result && (getTenantsNumber()
        == other.getTenantsNumber());
    result = result && (getOccupiedProperties()
        == other.getOccupiedProperties());
    result = result && (getWaitingQueue()
        == other.getWaitingQueue());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FREEPROPERTYAVAILABLE_FIELD_NUMBER;
    hash = (53 * hash) + getFreePropertyAvailable();
    hash = (37 * hash) + TENANTSNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getTenantsNumber();
    hash = (37 * hash) + OCCUPIEDPROPERTIES_FIELD_NUMBER;
    hash = (53 * hash) + getOccupiedProperties();
    hash = (37 * hash) + WAITINGQUEUE_FIELD_NUMBER;
    hash = (53 * hash) + getWaitingQueue();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.propertyMarket.TenantsVolatilityRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.propertyMarket.TenantsVolatilityRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.propertyMarket.TenantsVolatilityRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.propertyMarket.TenantsVolatilityRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.propertyMarket.TenantsVolatilityRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.propertyMarket.TenantsVolatilityRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.propertyMarket.TenantsVolatilityRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.propertyMarket.TenantsVolatilityRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.propertyMarket.TenantsVolatilityRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.propertyMarket.TenantsVolatilityRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.propertyMarket.TenantsVolatilityRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.propertyMarket.TenantsVolatilityRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.propertyMarket.TenantsVolatilityRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code propertyMarket.TenantsVolatilityRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:propertyMarket.TenantsVolatilityRequest)
      ds.propertyMarket.TenantsVolatilityRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.propertyMarket.propertyMarketImpl.internal_static_propertyMarket_TenantsVolatilityRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.propertyMarket.propertyMarketImpl.internal_static_propertyMarket_TenantsVolatilityRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.propertyMarket.TenantsVolatilityRequest.class, ds.propertyMarket.TenantsVolatilityRequest.Builder.class);
    }

    // Construct using ds.propertyMarket.TenantsVolatilityRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      freePropertyAvailable_ = 0;

      tenantsNumber_ = 0;

      occupiedProperties_ = 0;

      waitingQueue_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.propertyMarket.propertyMarketImpl.internal_static_propertyMarket_TenantsVolatilityRequest_descriptor;
    }

    @java.lang.Override
    public ds.propertyMarket.TenantsVolatilityRequest getDefaultInstanceForType() {
      return ds.propertyMarket.TenantsVolatilityRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ds.propertyMarket.TenantsVolatilityRequest build() {
      ds.propertyMarket.TenantsVolatilityRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.propertyMarket.TenantsVolatilityRequest buildPartial() {
      ds.propertyMarket.TenantsVolatilityRequest result = new ds.propertyMarket.TenantsVolatilityRequest(this);
      result.freePropertyAvailable_ = freePropertyAvailable_;
      result.tenantsNumber_ = tenantsNumber_;
      result.occupiedProperties_ = occupiedProperties_;
      result.waitingQueue_ = waitingQueue_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.propertyMarket.TenantsVolatilityRequest) {
        return mergeFrom((ds.propertyMarket.TenantsVolatilityRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.propertyMarket.TenantsVolatilityRequest other) {
      if (other == ds.propertyMarket.TenantsVolatilityRequest.getDefaultInstance()) return this;
      if (other.getFreePropertyAvailable() != 0) {
        setFreePropertyAvailable(other.getFreePropertyAvailable());
      }
      if (other.getTenantsNumber() != 0) {
        setTenantsNumber(other.getTenantsNumber());
      }
      if (other.getOccupiedProperties() != 0) {
        setOccupiedProperties(other.getOccupiedProperties());
      }
      if (other.getWaitingQueue() != 0) {
        setWaitingQueue(other.getWaitingQueue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.propertyMarket.TenantsVolatilityRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.propertyMarket.TenantsVolatilityRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int freePropertyAvailable_ ;
    /**
     * <code>int32 freePropertyAvailable = 1;</code>
     */
    public int getFreePropertyAvailable() {
      return freePropertyAvailable_;
    }
    /**
     * <code>int32 freePropertyAvailable = 1;</code>
     */
    public Builder setFreePropertyAvailable(int value) {
      
      freePropertyAvailable_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 freePropertyAvailable = 1;</code>
     */
    public Builder clearFreePropertyAvailable() {
      
      freePropertyAvailable_ = 0;
      onChanged();
      return this;
    }

    private int tenantsNumber_ ;
    /**
     * <code>int32 tenantsNumber = 2;</code>
     */
    public int getTenantsNumber() {
      return tenantsNumber_;
    }
    /**
     * <code>int32 tenantsNumber = 2;</code>
     */
    public Builder setTenantsNumber(int value) {
      
      tenantsNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 tenantsNumber = 2;</code>
     */
    public Builder clearTenantsNumber() {
      
      tenantsNumber_ = 0;
      onChanged();
      return this;
    }

    private int occupiedProperties_ ;
    /**
     * <code>int32 occupiedProperties = 3;</code>
     */
    public int getOccupiedProperties() {
      return occupiedProperties_;
    }
    /**
     * <code>int32 occupiedProperties = 3;</code>
     */
    public Builder setOccupiedProperties(int value) {
      
      occupiedProperties_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 occupiedProperties = 3;</code>
     */
    public Builder clearOccupiedProperties() {
      
      occupiedProperties_ = 0;
      onChanged();
      return this;
    }

    private int waitingQueue_ ;
    /**
     * <code>int32 waitingQueue = 4;</code>
     */
    public int getWaitingQueue() {
      return waitingQueue_;
    }
    /**
     * <code>int32 waitingQueue = 4;</code>
     */
    public Builder setWaitingQueue(int value) {
      
      waitingQueue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 waitingQueue = 4;</code>
     */
    public Builder clearWaitingQueue() {
      
      waitingQueue_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:propertyMarket.TenantsVolatilityRequest)
  }

  // @@protoc_insertion_point(class_scope:propertyMarket.TenantsVolatilityRequest)
  private static final ds.propertyMarket.TenantsVolatilityRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.propertyMarket.TenantsVolatilityRequest();
  }

  public static ds.propertyMarket.TenantsVolatilityRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TenantsVolatilityRequest>
      PARSER = new com.google.protobuf.AbstractParser<TenantsVolatilityRequest>() {
    @java.lang.Override
    public TenantsVolatilityRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TenantsVolatilityRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TenantsVolatilityRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TenantsVolatilityRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.propertyMarket.TenantsVolatilityRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

