// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: propertyMarket.proto

package ds.propertyMarket;

public interface TenantsVolatilityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:propertyMarket.TenantsVolatilityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string recommendation = 1;</code>
   */
  java.lang.String getRecommendation();
  /**
   * <code>string recommendation = 1;</code>
   */
  com.google.protobuf.ByteString
      getRecommendationBytes();
}
