// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buildingMaterial.proto

package ds.buildingMaterial;

public final class BuildingMaterialImpl {
  private BuildingMaterialImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buildingMaterial_MaterialRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buildingMaterial_MaterialRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buildingMaterial_MaterialResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buildingMaterial_MaterialResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buildingMaterial_MonitorLevels_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buildingMaterial_MonitorLevels_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buildingMaterial_LevelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buildingMaterial_LevelsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buildingMaterial_OrderMaterial_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buildingMaterial_OrderMaterial_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buildingMaterial_OrderMaterialResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buildingMaterial_OrderMaterialResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026buildingMaterial.proto\022\020buildingMateri" +
      "al\"%\n\017MaterialRequest\022\022\n\nmaterialId\030\001 \001(" +
      "\005\")\n\020MaterialResponse\022\025\n\rmaterialLevel\030\001" +
      " \001(\005\"#\n\rMonitorLevels\022\022\n\nmaterialId\030\001 \001(" +
      "\005\":\n\016LevelsResponse\022\022\n\nmaterialId\030\001 \001(\005\022" +
      "\024\n\014currentLevel\030\002 \001(\005\";\n\rOrderMaterial\022\022" +
      "\n\nmaterialId\030\001 \001(\005\022\026\n\016materialLevels\030\002 \001" +
      "(\005\"4\n\025OrderMaterialResponse\022\033\n\023currentMa" +
      "terialUsed\030\002 \001(\0052\270\002\n\020BuildingMaterial\022]\n" +
      "\022CheckMaterialLevel\022!.buildingMaterial.M" +
      "aterialRequest\032\".buildingMaterial.Materi" +
      "alResponse\"\000\022^\n\025MonitorMaterialLevels\022\037." +
      "buildingMaterial.MonitorLevels\032 .buildin" +
      "gMaterial.LevelsResponse\"\0000\001\022e\n\025SwitchTo" +
      "OrderMaterial\022\037.buildingMaterial.OrderMa" +
      "terial\032\'.buildingMaterial.OrderMaterialR" +
      "esponse\"\000(\001B-\n\023ds.buildingMaterialB\024Buil" +
      "dingMaterialImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_buildingMaterial_MaterialRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_buildingMaterial_MaterialRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buildingMaterial_MaterialRequest_descriptor,
        new java.lang.String[] { "MaterialId", });
    internal_static_buildingMaterial_MaterialResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_buildingMaterial_MaterialResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buildingMaterial_MaterialResponse_descriptor,
        new java.lang.String[] { "MaterialLevel", });
    internal_static_buildingMaterial_MonitorLevels_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_buildingMaterial_MonitorLevels_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buildingMaterial_MonitorLevels_descriptor,
        new java.lang.String[] { "MaterialId", });
    internal_static_buildingMaterial_LevelsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_buildingMaterial_LevelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buildingMaterial_LevelsResponse_descriptor,
        new java.lang.String[] { "MaterialId", "CurrentLevel", });
    internal_static_buildingMaterial_OrderMaterial_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_buildingMaterial_OrderMaterial_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buildingMaterial_OrderMaterial_descriptor,
        new java.lang.String[] { "MaterialId", "MaterialLevels", });
    internal_static_buildingMaterial_OrderMaterialResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_buildingMaterial_OrderMaterialResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buildingMaterial_OrderMaterialResponse_descriptor,
        new java.lang.String[] { "CurrentMaterialUsed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
