// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buildingMaterial.proto

package ds.buildingMaterial;

public interface MaterialResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:buildingMaterial.MaterialResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 materialLevel = 1;</code>
   */
  int getMaterialLevel();
}
