// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buildingMaterial.proto

package ds.buildingMaterial;

public interface MaterialRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:buildingMaterial.MaterialRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tankId = 1;</code>
   */
  int getTankId();
}
