// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buildingMaterial.proto

package ds.buildingMaterial;

public interface MonitorLevelsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:buildingMaterial.MonitorLevels)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 materialId = 1;</code>
   */
  int getMaterialId();
}
