// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buildingMaterial.proto

package ds.buildingMaterial;

public interface OrderMaterialOrBuilder extends
    // @@protoc_insertion_point(interface_extends:buildingMaterial.OrderMaterial)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 materialId = 1;</code>
   */
  int getMaterialId();

  /**
   * <code>int32 materialLevels = 2;</code>
   */
  int getMaterialLevels();
}
