// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buildingMaterial.proto

package ds.buildingMaterial;

public interface OrderMaterialResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:buildingMaterial.OrderMaterialResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 currentMaterialUsed = 2;</code>
   */
  int getCurrentMaterialUsed();
}
