// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buildingMaterial.proto

package ds.buildingMaterial;

public interface OrderMaterialOrBuilder extends
    // @@protoc_insertion_point(interface_extends:buildingMaterial.OrderMaterial)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tankId = 1;</code>
   */
  int getTankId();

  /**
   * <code>int32 tankLevels = 2;</code>
   */
  int getTankLevels();
}
