// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buildingMaterial.proto

package ds.buildingMaterial;

/**
 * Protobuf type {@code buildingMaterial.OrderMaterialResponse}
 */
public  final class OrderMaterialResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:buildingMaterial.OrderMaterialResponse)
    OrderMaterialResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OrderMaterialResponse.newBuilder() to construct.
  private OrderMaterialResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderMaterialResponse() {
    currentMaterialUsed_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OrderMaterialResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 16: {

            currentMaterialUsed_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.buildingMaterial.BuildingMaterialImpl.internal_static_buildingMaterial_OrderMaterialResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.buildingMaterial.BuildingMaterialImpl.internal_static_buildingMaterial_OrderMaterialResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.buildingMaterial.OrderMaterialResponse.class, ds.buildingMaterial.OrderMaterialResponse.Builder.class);
  }

  public static final int CURRENTMATERIALUSED_FIELD_NUMBER = 2;
  private int currentMaterialUsed_;
  /**
   * <code>int32 currentMaterialUsed = 2;</code>
   */
  public int getCurrentMaterialUsed() {
    return currentMaterialUsed_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (currentMaterialUsed_ != 0) {
      output.writeInt32(2, currentMaterialUsed_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (currentMaterialUsed_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, currentMaterialUsed_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.buildingMaterial.OrderMaterialResponse)) {
      return super.equals(obj);
    }
    ds.buildingMaterial.OrderMaterialResponse other = (ds.buildingMaterial.OrderMaterialResponse) obj;

    boolean result = true;
    result = result && (getCurrentMaterialUsed()
        == other.getCurrentMaterialUsed());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENTMATERIALUSED_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentMaterialUsed();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.buildingMaterial.OrderMaterialResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.buildingMaterial.OrderMaterialResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.buildingMaterial.OrderMaterialResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.buildingMaterial.OrderMaterialResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.buildingMaterial.OrderMaterialResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.buildingMaterial.OrderMaterialResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.buildingMaterial.OrderMaterialResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.buildingMaterial.OrderMaterialResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.buildingMaterial.OrderMaterialResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.buildingMaterial.OrderMaterialResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.buildingMaterial.OrderMaterialResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.buildingMaterial.OrderMaterialResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.buildingMaterial.OrderMaterialResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code buildingMaterial.OrderMaterialResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:buildingMaterial.OrderMaterialResponse)
      ds.buildingMaterial.OrderMaterialResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.buildingMaterial.BuildingMaterialImpl.internal_static_buildingMaterial_OrderMaterialResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.buildingMaterial.BuildingMaterialImpl.internal_static_buildingMaterial_OrderMaterialResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.buildingMaterial.OrderMaterialResponse.class, ds.buildingMaterial.OrderMaterialResponse.Builder.class);
    }

    // Construct using ds.buildingMaterial.OrderMaterialResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      currentMaterialUsed_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.buildingMaterial.BuildingMaterialImpl.internal_static_buildingMaterial_OrderMaterialResponse_descriptor;
    }

    @java.lang.Override
    public ds.buildingMaterial.OrderMaterialResponse getDefaultInstanceForType() {
      return ds.buildingMaterial.OrderMaterialResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.buildingMaterial.OrderMaterialResponse build() {
      ds.buildingMaterial.OrderMaterialResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.buildingMaterial.OrderMaterialResponse buildPartial() {
      ds.buildingMaterial.OrderMaterialResponse result = new ds.buildingMaterial.OrderMaterialResponse(this);
      result.currentMaterialUsed_ = currentMaterialUsed_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.buildingMaterial.OrderMaterialResponse) {
        return mergeFrom((ds.buildingMaterial.OrderMaterialResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.buildingMaterial.OrderMaterialResponse other) {
      if (other == ds.buildingMaterial.OrderMaterialResponse.getDefaultInstance()) return this;
      if (other.getCurrentMaterialUsed() != 0) {
        setCurrentMaterialUsed(other.getCurrentMaterialUsed());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.buildingMaterial.OrderMaterialResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.buildingMaterial.OrderMaterialResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int currentMaterialUsed_ ;
    /**
     * <code>int32 currentMaterialUsed = 2;</code>
     */
    public int getCurrentMaterialUsed() {
      return currentMaterialUsed_;
    }
    /**
     * <code>int32 currentMaterialUsed = 2;</code>
     */
    public Builder setCurrentMaterialUsed(int value) {
      
      currentMaterialUsed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 currentMaterialUsed = 2;</code>
     */
    public Builder clearCurrentMaterialUsed() {
      
      currentMaterialUsed_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:buildingMaterial.OrderMaterialResponse)
  }

  // @@protoc_insertion_point(class_scope:buildingMaterial.OrderMaterialResponse)
  private static final ds.buildingMaterial.OrderMaterialResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.buildingMaterial.OrderMaterialResponse();
  }

  public static ds.buildingMaterial.OrderMaterialResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderMaterialResponse>
      PARSER = new com.google.protobuf.AbstractParser<OrderMaterialResponse>() {
    @java.lang.Override
    public OrderMaterialResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OrderMaterialResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OrderMaterialResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderMaterialResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.buildingMaterial.OrderMaterialResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

